#!/bin/sh

# This file is part of OpenPanel - The Open Source Control Panel
# The Grace library is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, either version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

exec > rsrc/resources.xml
cat << __EOF
<?xml version="1.0" encoding="utf-8"?>
<opencore.rsrc>
  <dict id="errors">
    <dict id="en">
__EOF

perl -ne '
if (m!^#define (ERR_[^ ]+)\s+(0x[0-9a-f]+)\s*//\s*(.*)!)
{
	print "	  <string id=\"$2\">$3</string>\n";
}' < error.h

cat << __EOF
    </dict>
  </dict>
</opencore.rsrc>
__EOF
