#!/bin/sh
# postrm framework for openpanel packages
#
# see: dh_installdeb(1)

set -e


case "$1" in
    purge)
        update-rc.d openpanel-core remove > /dev/null
        rm -f /var/opencore/log/opencore.*
        rm -f /var/opencore/cache/module.cache
        rm -f /var/opencore/db/panel/panel.db
        rm -f /var/opencore/db/alertq.db
        rm -rf /var/opencore/conf/staging/*
        ;;
esac

#DEBHELPER#

exit 0


